/* Copyright © 2020. Financelime, https://financelime.com. All rights reserved.
   Author: DmAlix. Contacts: <dmalix@financelime.com>, <dmalix@yahoo.com>
   License: GNU General Public License v3.0, https://www.gnu.org/licenses/gpl-3.0.html */

CREATE TABLE IF NOT EXISTS "public"."confirmation_create_new_account" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 ),
	"created_at" TIMESTAMP ( 6 ) NOT NULL,
	"updated_at" TIMESTAMP ( 6 ) DEFAULT NULL :: TIMESTAMP WITHOUT TIME ZONE,
	"deleted_at" TIMESTAMP ( 6 ) DEFAULT NULL :: TIMESTAMP WITHOUT TIME ZONE,
	"email" VARCHAR ( 255 ) COLLATE "pg_catalog"."default" NOT NULL,
	"language" VARCHAR ( 5 ) COLLATE "pg_catalog"."default" NOT NULL,
	"link_key" VARCHAR ( 16 ) COLLATE "pg_catalog"."default" NOT NULL,
	"expires_at" TIMESTAMP ( 6 ) NOT NULL,
	"is_sent" bool NOT NULL DEFAULT FALSE,
	"remote_addr" VARCHAR ( 45 ) COLLATE "pg_catalog"."default" NOT NULL,
	CONSTRAINT "confirmation_create_new_account_pkey" PRIMARY KEY ( "id" )
);
ALTER TABLE "public"."confirmation_create_new_account" OWNER TO "financelime_user";
COMMENT ON TABLE "public"."confirmation_create_new_account" IS 'Email verification links';

CREATE TABLE IF NOT EXISTS "public"."confirmation_reset_password" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 ),
	"created_at" TIMESTAMP ( 6 ) NOT NULL,
	"updated_at" TIMESTAMP ( 6 ) DEFAULT NULL :: TIMESTAMP WITHOUT TIME ZONE,
	"deleted_at" TIMESTAMP ( 6 ) DEFAULT NULL :: TIMESTAMP WITHOUT TIME ZONE,
	"email" VARCHAR ( 255 ) COLLATE "pg_catalog"."default" NOT NULL,
	"language" VARCHAR ( 5 ) COLLATE "pg_catalog"."default" NOT NULL,
	"link_key" VARCHAR ( 16 ) COLLATE "pg_catalog"."default" NOT NULL,
	"expires_at" TIMESTAMP ( 6 ) NOT NULL,
	"remote_addr" VARCHAR ( 45 ) COLLATE "pg_catalog"."default" NOT NULL,
	"is_sent" bool NOT NULL DEFAULT FALSE,
	CONSTRAINT "confirmation_reset_password_pkey" PRIMARY KEY ( "id" )
);
ALTER TABLE "public"."confirmation_reset_password" OWNER TO "financelime_user";
COMMENT ON TABLE "public"."confirmation_reset_password" IS 'Password reset confirmation links';

CREATE TABLE IF NOT EXISTS "public"."invite_code_reserved" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 ),
	"created_at" TIMESTAMP ( 6 ) NOT NULL,
	"updated_at" TIMESTAMP ( 6 ) DEFAULT NULL :: TIMESTAMP WITHOUT TIME ZONE,
	"deleted_at" TIMESTAMP ( 6 ) DEFAULT NULL :: TIMESTAMP WITHOUT TIME ZONE,
	"invite_code_id" int4 NOT NULL,
	"email" VARCHAR ( 255 ) COLLATE "pg_catalog"."default" NOT NULL,
	"confirmation_id" int4 NOT NULL,
	CONSTRAINT "invite_code_reserved_pkey" PRIMARY KEY ( "id" )
);
ALTER TABLE "public"."invite_code_reserved" OWNER TO "financelime_user";
COMMENT ON TABLE "public"."invite_code_reserved" IS 'List of reserved Invite Codes';

CREATE TABLE IF NOT EXISTS "public"."notification_email" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 ),
	"created_at" TIMESTAMP ( 6 ) NOT NULL,
	"updated_at" TIMESTAMP ( 6 ) DEFAULT NULL :: TIMESTAMP WITHOUT TIME ZONE,
	"deleted_at" TIMESTAMP ( 6 ) DEFAULT NULL :: TIMESTAMP WITHOUT TIME ZONE,
	"language" VARCHAR ( 5 ) COLLATE "pg_catalog"."default" NOT NULL,
	"email" VARCHAR ( 255 ) COLLATE "pg_catalog"."default" NOT NULL,
	"subject" TEXT COLLATE "pg_catalog"."default" NOT NULL,
	"body" TEXT COLLATE "pg_catalog"."default" NOT NULL,
	"priority" int2 NOT NULL DEFAULT 0,
	"is_sent" bool NOT NULL DEFAULT FALSE,
	CONSTRAINT "notification_email_pkey" PRIMARY KEY ( "id" )
);
ALTER TABLE "public"."notification_email" OWNER TO "financelime_user";
COMMENT ON TABLE "public"."notification_email" IS 'Email notifications';

