CREATE TABLE IF NOT EXISTS "public"."user" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 ),
	"created_at" TIMESTAMP ( 6 ) NOT NULL,
	"updated_at" TIMESTAMP ( 6 ),
	"deleted_at" TIMESTAMP ( 6 ),
	"email" VARCHAR ( 255 ) COLLATE "pg_catalog"."default" NOT NULL,
	"language" VARCHAR ( 5 ) COLLATE "pg_catalog"."default" NOT NULL,
	"password" VARCHAR ( 64 ) COLLATE "pg_catalog"."default" NOT NULL,
	CONSTRAINT "user_pkey" PRIMARY KEY ( "id" )
);
ALTER TABLE "public"."user" OWNER TO "financelime_user";
COMMENT ON TABLE "public"."user" IS 'User List';

CREATE TABLE IF NOT EXISTS "public"."session" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 ),
	"created_at" TIMESTAMP ( 6 ) NOT NULL,
	"updated_at" TIMESTAMP ( 6 ) DEFAULT NULL :: TIMESTAMP WITHOUT TIME ZONE,
	"deleted_at" TIMESTAMP ( 6 ) DEFAULT NULL :: TIMESTAMP WITHOUT TIME ZONE,
	"user_id" int4 NOT NULL,
	"client_id" VARCHAR ( 32 ) COLLATE "pg_catalog"."default" NOT NULL,
	"remote_addr" VARCHAR ( 45 ) COLLATE "pg_catalog"."default" NOT NULL,
	"public_id" VARCHAR ( 64 ) COLLATE "pg_catalog"."default" NOT NULL,
	"hashed_refresh_token" VARCHAR ( 64 ) COLLATE "pg_catalog"."default" NOT NULL,
	CONSTRAINT "session_pkey" PRIMARY KEY ( "id" )
);
ALTER TABLE "public"."session" OWNER TO "financelime_user";
COMMENT ON TABLE "public"."session" IS 'Session List';

CREATE TABLE IF NOT EXISTS "public"."device" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 ),
	"created_at" TIMESTAMP ( 6 ) NOT NULL,
	"updated_at" TIMESTAMP ( 6 ) DEFAULT NULL :: TIMESTAMP WITHOUT TIME ZONE,
	"deleted_at" TIMESTAMP ( 6 ) DEFAULT NULL :: TIMESTAMP WITHOUT TIME ZONE,
	"session_id" int4 NOT NULL,
	"platform" TEXT COLLATE "pg_catalog"."default",
	"height" int2,
	"width" int2,
	"language" TEXT COLLATE "pg_catalog"."default",
	"timezone" TEXT COLLATE "pg_catalog"."default",
	"user_agent" TEXT COLLATE "pg_catalog"."default",
	CONSTRAINT "device_pkey" PRIMARY KEY ( "id" )
);
ALTER TABLE "public"."device" OWNER TO "financelime_user";
COMMENT ON TABLE "public"."device" IS 'Device List';

CREATE TABLE IF NOT EXISTS "public"."invite_code" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 ),
	"created_at" TIMESTAMP ( 6 ) NOT NULL,
	"updated_at" TIMESTAMP ( 6 ),
	"deleted_at" TIMESTAMP ( 6 ),
	"user_id" int4 NOT NULL,
	"expires_at" TIMESTAMP ( 6 ) NOT NULL,
	"number_limit" int2 NOT NULL,
	"value" VARCHAR ( 16 ) COLLATE "pg_catalog"."default" NOT NULL,
	CONSTRAINT "invite_code_pkey" PRIMARY KEY ( "id" )
);
ALTER TABLE "public"."invite_code" OWNER TO "financelime_user";
COMMENT ON TABLE "public"."invite_code" IS 'Invite Codes List';

CREATE TABLE IF NOT EXISTS "public"."invite_code_issued" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 ),
	"created_at" TIMESTAMP ( 6 ) NOT NULL,
	"updated_at" TIMESTAMP ( 6 ) DEFAULT NULL :: TIMESTAMP WITHOUT TIME ZONE,
	"deleted_at" TIMESTAMP ( 6 ) DEFAULT NULL :: TIMESTAMP WITHOUT TIME ZONE,
	"invite_code_id" int4 NOT NULL,
	"user_id" int4 NOT NULL,
	CONSTRAINT "invite_code_issued_pkey" PRIMARY KEY ( "id" )
);
ALTER TABLE "public"."invite_code_issued" OWNER TO "financelime_user";
COMMENT ON TABLE "public"."invite_code_issued" IS 'Issued Invite Codes List';
